export const LOAD_MESSAGES = 'LOAD_MESSAGES';

export const LOAD_COUNTS = 'LOAD_COUNTS';

export const ALERT_ERRORS = 'ALERT_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADD_TRANSLATION = 'ADD_TRANSLATION';
export const LOAD_TRANSLATIONS = 'LOAD_TRANSLATIONS';
export const REMOVE_TRANSLATION = 'REMOVE_TRANSLATION';
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION';
